name: Build & Deploy

# on:
#   workflow_dispatch:
on:
  push:
    branches: main
#  release:
#    types: [ published ]  # This will trigger the workflow on newly published releases


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [ "20" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install packages
        run: npm ci

      - name: Run npm build for gh-pages
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com